fail_fast: true

repos:
  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place, --make-summary-multi-line, --close-quotes-on-newline, --wrap-summaries, "88"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [
            "hypothesis",
            "package-dev-utils",
            "pytest-mypy-plugins",
            "quinten-cli",
            "simple-classproperty",
            "types-python-slugify",
            "types-requests",
            "types-toml",
        ]
  - repo: https://github.com/quintenroets/package-dev-tools
    rev: f47ff2e
    hooks:
      - id: check-coverage
  - repo: https://github.com/quintenroets/package-dev-tools
    rev: c11f0ab
    hooks:
      - id: check-shields
  - repo: https://github.com/quintenroets/package-dev-tools
    rev: c11f0ab
    hooks:
      - id: check-version


ci:
    autofix_commit_msg: auto fixes from pre-commit.com hooks
    autoupdate_commit_msg: 'pre-commit autoupdate'
