fail_fast: true

repos:
  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place, --make-summary-multi-line, --close-quotes-on-newline, --wrap-summaries, "88"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [
          "package-dev-tools >= 0.3.4, <1",
          "hypothesis >=6.91.0, <7",
          "package-dev-utils >=0.1.6, <1",
          "pytest-mypy-plugins >=3.0.0, <4",
          "quinten-cli >=1.1.12, <2",
          "simple-classproperty >=4.0.2, <5",
          "types-python-slugify >=8.0.0.3, <9",
          "types-requests >=2.31.0, <3",
          "types-toml >=0.10.8, <1",
        ]
  - repo: local
    hooks:
      - id: run-tests
        name: run-tests
        entry: coverage run
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/quintenroets/package-dev-tools
    rev: v0.3.1
    hooks:
      - id: check-coverage
  - repo: https://github.com/quintenroets/package-dev-tools
    rev: v0.3.1
    hooks:
      - id: check-shields
  - repo: https://github.com/quintenroets/package-dev-tools
    rev: v0.3.1
    hooks:
      - id: check-version

ci:
    autofix_commit_msg: auto fixes from pre-commit.com hooks
    autoupdate_commit_msg: 'pre-commit autoupdate'
