repos:
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place, --make-summary-multi-line, --close-quotes-on-newline, --wrap-summaries, "88"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/quintenroets/package-dev-tools
    rev: v0.6.9
    hooks:
      - id: infer-missing-annotations
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        files: '\.py'
        fail_fast: true
        require_serial: true
      - id: run-tests
        name: run-tests
        entry: coverage run
        language: system
        pass_filenames: false
        always_run: true
        fail_fast: true
  - repo: https://github.com/quintenroets/package-dev-tools
    rev: v0.6.9
    hooks:
      - id: check-coverage
      - id: check-shields
      - id: check-version

ci:
    autofix_commit_msg: auto fixes from pre-commit hooks
    autoupdate_commit_msg: 'pre-commit auto updates'
    autoupdate_schedule: monthly
    skip: [mypy, run-tests, check-coverage]
