name: Trigger template sync

on:
  push:
    branches:
      - main
jobs:
  trigger-template-sync:
    runs-on: ubuntu-latest
    if: github.repository == 'quintenroets/python-package-template'
    steps:
      - name: Trigger template sync
        uses: quintenroets/actions/trigger-template-sync@main
        with:
          token: ${{ secrets.TEMPLATE_SYNC_TRIGGER }}
